-- matchingsテーブルにZOOM・返金関連カラムを追加
ALTER TABLE public.matchings
  ADD COLUMN IF NOT EXISTS zoom_url TEXT,
  ADD COLUMN IF NOT EXISTS zoom_scheduled_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS zoom_sent BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS zoom_sent_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS payment_intent_id TEXT,
  ADD COLUMN IF NOT EXISTS refunded BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS refunded_at TIMESTAMPTZ;
